package site.liangbai.forgeeventbridge.asm.constantsprovider;

public enum Constant {
    EVENT_HOLDER_CLASS_NAME,
    EVENT_HOLDER_CLASS_NAME_L,
    SUBSCRIBE_EVENT_CLASS_NAME,
    EVENT_PRIORITY_CLASS_NAME,
    EVENT_WRAPPER_CREATOR_CLASS_NAME,
    WRAPPER_CREATOR_CLASS_NAME_L,
    WRAPPER_CREATORS_CLASS_NAME_L
}
