issueTrackerURL = "https://github.com/Liangbai2333/forge-event-bridge/issues"
license = "GPL v3.0"
loaderVersion = "[31,)"
modLoader = "javafml"

[[mods]]
authors = "Liangbai"
credits = "Liangbai"
description = '''
    Help Bukkit plugins listen to mod events.
    '''
displayName = "Forge-Event-Bridge"
modId = "forgeeventbridge"
version = "${file.jarVersion}"

[[dependencies.forgeeventbridge]]
mandatory = true
modId = "forge"
ordering = "NONE"
side = "SERVER"
versionRange = "[31,)"
